version: '3.8'

services:
  frontend:
    build: .
    image: adiwijayajy/wayshub-frontend:prod
    container_name: wayshub-fe
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
